### ISSUE TITLE
Problems with Let's Encrypt cert issuance

### ISSUE THREAD

**Issue by alento-group** [jrsupplee/mailinabox#1]
Hi,

I installed the quota version and now have run into this ... I am not certain where to start to look to debug as it is something I have not seen yet on the MiaB forum ... thoughts?

A link to the discussion at LE:

https://community.letsencrypt.org/t/another-caa-record-failure-issue/86388/10

**Comment by jrsupplee** [comment]
This version of MiaB does not make any changes to the DNS stuff from the standard version.

Did you make manual changes to `dns/custom.yaml`?  If it is not valid YAML it might be ignored completely.

**Comment by jrsupplee** [comment]
I just looked at the code.  If it is not valid YAML it will be ignored.  Try checking your YAML at yamllint.com to check if it is valid.

**Comment by alento-group** [comment]
Hmm, seems it is valid ... I have never seen anything quite like this before.  I think that I am just going to destroy the VPS and start over.

**Comment by jrsupplee** [comment]
Have you tried running setup (`mailinabox`) again?  The DNS is only rewritten by the setup process.

**Comment by alento-group** [comment]
Yes.  A few times during the several hours I was messing with it.
The issue has been resolved.  You can see it on the LE thread, but a short summary is if you ONLY have emails that deliver to a subdomain (email@box.example.com) then the LE search for a CAA record will fail as it is looking for the naked domain's zone file, which is not there.
