### ISSUE TITLE
version 0.44-quota-0.20-beta ??

### ISSUE THREAD

**Issue by JohnJ007** [jrsupplee/mailinabox#10]
I am getting a strange error message to the update. I tried the following:

1. Downloaded the 0.44 version for Josh.
2. Moved my install of quota into another directory
3. Installed josh’s version
4. Cloned Jrsupplee’s version of 0.44,
5. But with the following script sudo bash setup/bootstrap.sh, i keep getting the same error
6. I ran sudo setup/start.sh, and that upgraded me to v0.44-quota-0.20-beta
7. On status check, it states the following error "A new version of Mail-in-a-Box is available. You are running version v0.44-quota-0.20-beta. The latest version is v0.44-quota-0.22-beta. For upgrade instructions, see https://github.com/jrsupplee/mailinabox/blob/master/README.md. "

So now, atleast my QUOTA are working.

But how do I go from v0.44-quota-0.20-beta to v0.44-quota-0.22-beta
The script: sudo bash setup/bootstrap.sh, keeps giving me the following error:

Updating Mail-in-a-Box to v0.44-quota-0.22-beta . . .
fatal: Couldn’t find remote ref refs/tags/v0.44-quota-0.22-beta
error: pathspec ‘v0.44-quota-0.22-beta’ did not match any file(s) known to git.
Update failed. Did you modify something in /root/mailinabox?

Any help at all on this error, would be really really helpful :slight_smile: … I’m willing to try

**Comment by jrsupplee** [comment]
The tag was misnamed.  `v0.44-quota-0.22-beta` is the correct tag and I have tagged the HEAD of the repository with it.  This should solve your problem after another `git pull`

**Comment by JohnJ007** [comment]
> The tag was misnamed. `v0.44-quota-0.22-beta` is the correct tag and I have tagged the HEAD of the repository with it. This should solve your problem after another `git pull`

Thank you so much. That fixed it :)

**Comment by JohnJ007** [comment]
And I'll clost this now.
