### ISSUE TITLE
Merge with 0.48

### ISSUE THREAD

**Issue by BiggerCookie** [jrsupplee/mailinabox#12]
Hi John.  Hope you are well and have not picked up COVID 19. 

Patiently waiting for the latest merge. 

Dennis

**Comment by jrsupplee** [comment]
Merged changes for v0.48

**Comment by BiggerCookie** [comment]
Thanks, John.  What do you think about proceeding to 0.50?

I appreciate your efforts.  

I have been really worried that you might have been taken by COVID.  

I live 3 miles south of Chattanooga.  You are just up the road a bit.  


Dennis

**Comment by BiggerCookie** [comment]
Issue?

Updating Mail-in-a-Box to v0.48-quota-0.22-beta . . .
fatal: Couldn't find remote ref refs/tags/v0.48-quota-0.22-beta
error: pathspec 'v0.48-quota-0.22-beta' did not match any file(s) known to git.
Update failed. Did you modify something in /home/ubuntu/mailinabox?
