### ISSUE TITLE
Update to 0.48 didn't work

### ISSUE THREAD

**Issue by DWomack** [jrsupplee/mailinabox#13]
![image](https://user-images.githubusercontent.com/7165493/95340424-2508be00-0883-11eb-8bc1-ad3a25c699fa.png)

**Comment by DWomack** [comment]
John, glad to see you back.  Worried COVID might have taken you.

**Comment by DWomack** [comment]
Tried to upgrade a second server and got the same result.

Dennis

**Comment by jrsupplee** [comment]
pushed the tag to the repository

**Comment by BiggerCookie** [comment]
That fixed it!

Thanks, John.

**Comment by stylnchris** [comment]
John can you PLEASE  update   mailinabox-extras to   v0.50

Regards,

Christopher Catucci

**Comment by DWomack** [comment]
All three of my servers running MiaB with Quotas updated fine
