### ISSUE TITLE
Upgrading current 0.40 install

### ISSUE THREAD

**Issue by uksitebuilder** [jrsupplee/mailinabox#2]
Hi

I am interested in adding Quota support to my MiaB installation

In the instructions you posted in the README for updating 0.40 to 0.40-Quota you said to rename the current mailinabox folder to miab.old (or similar)

Which folder would that be that needs renaming please, as I don’t want to mess this up :-)

**Comment by jrsupplee** [comment]
When you log into your machine there should be a folder named mailinabox.  At least that is the standard name.

**Comment by uksitebuilder** [comment]
In the home folder there is a user-data folder with the following:

Could not see a mailinabox folder

![image](https://user-images.githubusercontent.com/1906020/53165508-da153680-35ca-11e9-934a-e447f1af141d.png)

**Comment by uksitebuilder** [comment]
Found it, it was in /root
