### ISSUE TITLE
Did something stupid, now how do I upgrade? :p

### ISSUE THREAD

**Issue by alento-group** [jrsupplee/mailinabox#3]
Ok, don't know why I did it but I was on autopilot and followed Josh's instructions to upgrade.  As soon as the upgrade started I realized my mistake and aborted.  I think that his repository was downloaded, but nothing was installed.  So ... here I am.  When I follow the correct instructions, I get this:

> 
> root@box:/home/miab# cd mailinabox/
> root@box:/home/miab/mailinabox# git pull
> remote: Enumerating objects: 163, done.
> remote: Counting objects: 100% (100/100), done.
> remote: Compressing objects: 100% (19/19), done.
> remote: Total 43 (delta 33), reused 34 (delta 24), pack-reused 0
> Unpacking objects: 100% (43/43), done.
> From https://github.com/jrsupplee/mailinabox
>    2b70277..adf7a31  master                 -> origin/master
>  * [new tag]         v0.41-quota-0.17-alpha -> v0.41-quota-0.17-alpha
>  * [new tag]         v0.41                  -> v0.41
>  * [new tag]         v0.41-quota-0.16-alpha -> v0.41-quota-0.16-alpha
> You are not currently on a branch.
> Please specify which branch you want to merge with.
> See git-pull(1) for details.
> 
>     git pull <remote> <branch>
> 
> root@box:/home/miab/mailinabox# 
> 

How do I proceed?

**Comment by jrsupplee** [comment]
It looks like you are not on a branch.  If you run `git status` it should say which branch you are on.

Try doing a git pull, do a `git checkout master` before the `git pull`

**Comment by alento-group** [comment]
```
root@box:/home/miab/mailinabox# git status
HEAD detached at v0.40-quota-0.16-alpha
nothing to commit, working tree clean
root@box:/home/miab/mailinabox# 

```

**Comment by alento-group** [comment]
```
root@box:/home/miab/mailinabox# git checkout master
Previous HEAD position was 7f8336e Fix bug with quota input that prevented adding users
Switched to branch 'master'
Your branch is behind 'origin/master' by 1608 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
```

**Comment by alento-group** [comment]
Ok, I am good to go now!  Thanks!!!!!!!!!!!!
