### ISSUE TITLE
MiaB v0.42b released.  Upgrade path?

### ISSUE THREAD

**Issue by alento-group** [jrsupplee/mailinabox#5]
@jrsupplee Hi John,

MiaB v0.42b is released ... will you be upgrading this?

**Comment by stylnchris** [comment]
Hi John,  I think a bit more people use your fork then you probably think.   I too as well would like to see the upgrade of v0.42b merged in with quota fork.  I realize your probably need time to complete this work, was wondering if you were still willing to do it or if this fork is not going to be maintained.  

Thanks again for the fork.  Honestly I wish it was something that Josh would just roll into his version.

**Comment by jrsupplee** [comment]
I have upgrade the repository to include the changes in v0.42b.  Follow the instructions in the README to upgrade

**Comment by alento-group** [comment]
Thank you kind sir! :)
