### ISSUE TITLE
API support

### ISSUE THREAD

**Issue by na2axl** [jrsupplee/mailinabox#6]
Thanks @jrsupplee for this helpful patch on MiaB. I've seen that the only way to manage quota is through command line, there is any way to do the same job through APIs ? Or do you plan a feature like that ?

**Comment by na2axl** [comment]
Hi @jrsupplee, I've just started to use your patch and I've browsed the sources, I've found the way to use APIs :grin:, but I think you can add it on the README...

Thanks and feel free to close this issue.

**Comment by jrsupplee** [comment]
I am not sure where the API documentation is located for mail-in-a-box.  It is not in the README.  Have you found documentation for the rest of the API?

**Comment by ctrl-i** [comment]
Perhaps @na2axl means something like [this](https://github.com/mail-in-a-box/mailinabox/blob/a70ba94b0c2fb77f3f7c23f91eee5d4f3c1620f7/management/templates/custom-dns.html#L103)?

**Comment by na2axl** [comment]
Yes @ctrl-i is totally what I want. Since this patch comes with a totally new feature, It will be nice if it have an API documentation in the Users page like any other MiaB functionnalities (I principally use the API to automate tasks without accessing the MiaB CP).

**Comment by jrsupplee** [comment]
@ctrl-i this is the API documentation for DNS. As far as I know there is no documentation for the General API. If there is, please give me a link.

**Comment by ctrl-i** [comment]
> @ctrl-i this is the API documentation for DNS. As far as I know there is no documentation for the General API. If there is, please give me a link.

I think that is just the general thing that was wanted not the actual documentation.  There are similar things for a lot of the API in the MIAB HTML pages and I think @na2axl was wanting something similar for the quotas.

**Comment by jrsupplee** [comment]
> @ctrl-i: There are similar things for a lot of the API in the MIAB HTML pages

Link please

**Comment by ctrl-i** [comment]
> > @ctrl-i: There are similar things for a lot of the API in the MIAB HTML pages
> 
> Link please

I give up, I was only trying to help.

**Comment by jrsupplee** [comment]
> @ctrl-i: I give up, I was only trying to help.

My point is, with the exception of the DNS API, that there is no API documentation that I have seen.  @na2axl went to the source code to understand the API which is how everyone must do it.  I do not think having documentation for just the quota functions that were added will be very useful.

However, if someone is willing to write up some documentation I will put in the README

**Comment by jrsupplee** [comment]
So I found that there is documentation for the mail users API on the mail users' page.  I updated the documentation for the quota extensions and released a new version.
