### ISSUE TITLE
set quota action still visible for archived accounts

### ISSUE THREAD

**Issue by na2axl** [jrsupplee/mailinabox#7]
Hi @jrsupplee 
It seems that when we archive an email account, the `set quota` action is still visible.

![image](https://user-images.githubusercontent.com/14062034/66576743-83b83080-eb78-11e9-8a48-fae3976ad60d.png)

**Comment by jrsupplee** [comment]
Fixed in latest release

**Comment by na2axl** [comment]
Thanks :grin:
